name: laundryhouse_app
description: "LaundryHouse - Premium laundry service app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.8.4
  http: ^1.5.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.0.2
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  flutter_local_notifications: ^18.0.1
  audioplayers: ^6.1.0
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.9

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#9333EA"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
